name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: ajithkumargani
          outputs: dist/github-contribution-grid-snake.svg

      - name: Set permissions for dist folder
        run: chmod -R u+w dist  # Grant write permission

      - name: Generate dark mode version
        run: cp --no-preserve=mode,ownership dist/github-contribution-grid-snake.svg dist/github-contribution-grid-snake-dark.svg

      - name: Upload to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output  # Use 'output' branch for GitHub Pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
